-- ==========================================================
-- Migration: 001_auth_system_closure.sql
-- 描述: 完善理发师与管理员的鉴权系统，实现权限闭环
-- ==========================================================

-- 1. 扩充理发师表凭证 (如果已存在则跳过)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'app_barbers' AND COLUMN_NAME = 'phone') THEN
        ALTER TABLE app_barbers ADD COLUMN phone TEXT UNIQUE;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'app_barbers' AND COLUMN_NAME = 'password_hash') THEN
        ALTER TABLE app_barbers ADD COLUMN password_hash TEXT;
    END IF;
END $$;

-- 2. 创建管理员表
CREATE TABLE IF NOT EXISTS app_admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE, -- 用于登录，如 admin
  phone TEXT UNIQUE,
  password_hash TEXT,
  avatar TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. 开启 RLS 权限保护
ALTER TABLE app_admins ENABLE ROW LEVEL SECURITY;

-- 4. 插入初始管理员 (账号: admin, 初始密码: 123456)
-- 密码哈希: SHA-256 ('123456') = 8d969eee766982198004d0d900cfc1e2ee60b05b4bd5a7e7041b8900c2438c7f
INSERT INTO app_admins (name, username, password_hash) 
VALUES ('系统管理员', 'admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92')
ON CONFLICT (username) DO NOTHING;

-- 5. 初始权限策略
CREATE POLICY "Allow All for Admins" ON app_admins FOR ALL USING (true) WITH CHECK (true);

-- 6. 核心结算优化 (RPC) - 同步至 V2 以便支持更高的吞吐量
CREATE OR REPLACE FUNCTION complete_barber_service_v2(
    p_appointment_id BIGINT,
    p_customer_name TEXT,
    p_barber_name TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_customer_id BIGINT;
    v_vouchers INTEGER;
    v_used_voucher BOOLEAN := FALSE;
BEGIN
    SELECT id, vouchers INTO v_customer_id, v_vouchers 
    FROM app_customers WHERE name = p_customer_name;

    IF v_vouchers > 0 THEN
        UPDATE app_customers SET vouchers = vouchers - 1 WHERE id = v_customer_id;
        UPDATE app_barbers SET voucher_revenue = COALESCE(voucher_revenue, 0) + 1 WHERE name = p_barber_name;
        v_used_voucher := TRUE;
    END IF;

    UPDATE app_appointments SET status = 'completed', used_voucher = v_used_voucher WHERE id = p_appointment_id;
    RETURN jsonb_build_object('success', TRUE, 'used_voucher', v_used_voucher);
END;
$$;
