-- ==========================================================
-- BarberBook Pro - 性能优化数据库初始化脚本
-- 平台: PostgreSQL (Supabase)
-- ==========================================================

-- 1. 清理现有表 (慎用：仅用于全新安装)
-- DROP TABLE IF EXISTS app_ratings CASCADE;
-- DROP TABLE IF EXISTS app_services CASCADE;
-- DROP TABLE IF EXISTS app_settings CASCADE;
-- DROP TABLE IF EXISTS app_logs CASCADE;
-- DROP TABLE IF EXISTS app_appointments CASCADE;
-- DROP TABLE IF EXISTS app_customers CASCADE;
-- DROP TABLE IF EXISTS app_barbers CASCADE;

-- 2. 创建理发师表
CREATE TABLE IF NOT EXISTS app_barbers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT UNIQUE, -- 新增：用于登录
  password_hash TEXT, -- 新增：用于加密存储密码
  title TEXT,
  rating FLOAT DEFAULT 5.0,
  image TEXT,
  status TEXT DEFAULT 'active',
  specialties TEXT[],
  schedule INTEGER[],
  experience INTEGER DEFAULT 1,
  service_count INTEGER DEFAULT 0,
  voucher_revenue INTEGER DEFAULT 0,
  bio TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. 创建顾客表
CREATE TABLE IF NOT EXISTS app_customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  real_name TEXT,
  phone TEXT NOT NULL UNIQUE,
  email TEXT,
  avatar TEXT,
  password_hash TEXT,
  vouchers INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3.5 创建管理员表
CREATE TABLE IF NOT EXISTS app_admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE, -- 用于登录，如 admin
  phone TEXT UNIQUE,
  password_hash TEXT,
  avatar TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 初始管理员数据 (密码哈希由于是 SHA-256 '123456', 值为: 8d969eee766982198004d0d900cfc1e2ee60b05b4bd5a7e7041b8900c2438c7f)
INSERT INTO app_admins (name, username, password_hash) 
VALUES ('系统管理员', 'admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92')
ON CONFLICT (username) DO NOTHING;

-- 4. 创建预约记录表 (重度优化目标)
CREATE TABLE IF NOT EXISTS app_appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT,
  barber_name TEXT,
  service_name TEXT,
  date_str TEXT,
  time_str TEXT,
  price NUMERIC,
  status TEXT DEFAULT 'pending', -- 流转状态: pending, confirmed, checked_in, completed, cancelled
  used_voucher BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. 创建日志表
CREATE TABLE IF NOT EXISTS app_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" TEXT,
  role TEXT,
  action TEXT,
  details TEXT,
  type TEXT,
  avatar TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. 创建配置表
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. 创建服务套餐表
CREATE TABLE IF NOT EXISTS app_services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  duration INTEGER NOT NULL,
  icon TEXT DEFAULT 'content_cut',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. 创建评价表
CREATE TABLE IF NOT EXISTS app_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL,
  barber_name TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  rating INTEGER NOT NULL,
  attitude_rating INTEGER DEFAULT 5,
  skill_rating INTEGER DEFAULT 5,
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================================
-- 性能优化：索引设计
-- ==========================================================

-- 优化大屏轮询与实时叫号：针对日期和状态的复合索引
CREATE INDEX IF NOT EXISTS idx_appointments_monitor 
ON app_appointments (date_str, status) 
WHERE status != 'completed' AND status != 'cancelled';

-- 优化理发师队列展示：针对理发师名和日期的复合索引
CREATE INDEX IF NOT EXISTS idx_appointments_barber_queue 
ON app_appointments (barber_name, date_str);

-- 优化顾客历史记录查询
CREATE INDEX IF NOT EXISTS idx_appointments_customer 
ON app_appointments (customer_name);

-- 优化理发师查找
CREATE INDEX IF NOT EXISTS idx_barbers_status 
ON app_barbers (status);

-- 优化搜索与唯一标识（手机号已设为唯一索引）
CREATE INDEX IF NOT EXISTS idx_customers_name ON app_customers (name);

-- 优化日志查询：按时间倒序
CREATE INDEX IF NOT EXISTS idx_logs_created_at ON app_logs (created_at DESC);

-- ==========================================================
-- 安全策略 (RLS)
-- ==========================================================
ALTER TABLE app_barbers ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_ratings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Access" ON app_barbers FOR SELECT USING (true);
CREATE POLICY "Public Access" ON app_services FOR SELECT USING (true);
CREATE POLICY "Allow All" ON app_appointments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON app_customers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON app_admins FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON app_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON app_settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON app_ratings FOR ALL USING (true) WITH CHECK (true);

-- ==========================================================
-- 初期数据建议 (Optional)
-- ==========================================================
-- INSERT INTO app_settings (key, value) VALUES ('business_config', '{"openTime": "09:00", "closeTime": "21:00"}');

-- ==========================================================
-- 核心优化：原子化结算函数 (RPC)
-- ==========================================================
-- 该函数在单次数据库往返中完成：1. 检查凭证 2. 扣除凭证 3. 增加理发师业绩 4. 更新预约状态
CREATE OR REPLACE FUNCTION complete_barber_service_v2(
    p_appointment_id BIGINT,
    p_customer_name TEXT,
    p_barber_name TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER -- 确保有权限跨表更新
AS $$
DECLARE
    v_customer_id BIGINT;
    v_vouchers INTEGER;
    v_used_voucher BOOLEAN := FALSE;
BEGIN
    -- 1. 获取客户凭证信息
    SELECT id, vouchers INTO v_customer_id, v_vouchers 
    FROM app_customers 
    WHERE name = p_customer_name;

    -- 2. 处理凭证（如果有则扣除）
    IF v_vouchers > 0 THEN
        UPDATE app_customers 
        SET vouchers = vouchers - 1 
        WHERE id = v_customer_id;
        
        -- 更新理发师业绩 (增加业绩计数)
        UPDATE app_barbers 
        SET voucher_revenue = COALESCE(voucher_revenue, 0) + 1 
        WHERE name = p_barber_name;
        
        v_used_voucher := TRUE;
    END IF;

    -- 3. 更新预约状态
    UPDATE app_appointments 
    SET status = 'completed', used_voucher = v_used_voucher 
    WHERE id = p_appointment_id;

    -- 4. 返回结果
    RETURN jsonb_build_object('success', TRUE, 'used_voucher', v_used_voucher);
END;
$$;
